/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.product.app;

public class App {

    public static void main(String[] args) {
    	Product car = new Product().setName("Tata Nexon").setDescription("EV Car").setPrice(2000000D);
        System.out.println(car);
    }
}
